spring:
  application:
    name: hr-app
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: rh-backend
            client-secret: cgKvfELDgyYywFvo6NAMYEqkkrO0eqID
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/RH-Realm

server:
  port: 8083
