spring:
  application:
    name: hr-app

  datasource:
    url: jdbc:postgresql://localhost:5432/hr_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8083

# ✅ Keycloak Admin Client (for programmatic user/role management)
keycloak:
  admin:
    server-url: http://localhost:9090
    realm: RH-Realm
    client-id: keycloak-admin
    client-secret: "6Sj9xauDxSpoBCfHXHjp12SsuMqzyOHt"
