spring:
  application:
    name: hr-app

  datasource:
    url: jdbc:postgresql://localhost:5432/hr_db?currentSchema=app
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: app  # tell Hibernate that NEW tables it generates belong in `app`

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/RH-Realm  # 👈 This is the public URL for JWT validation
#          jwk-set-uri: http://localhost:9090/realms/RH-Realm/protocol/openid-connect/certs

  mail:
    host: smtp.gmail.com
    port: 587
    username: dachraouia193@gmail.com
    password: iiun fhvz ertn dopm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

file:
  upload-dir: ./uploads

server:
  port: 8083

logging:
  level:
    org.springframework.security: DEBUG

# ticket time to resolve
tickets:
  sla:
    overdue-hours: 72     # escalate after 3 day

# ✅ Keycloak Admin Client (for managing users/roles via Admin API)
keycloak:
  admin:
    server-url: http://localhost:9090
    realm: RH-Realm
    client-id: keycloak-admin
    client-secret: "6Sj9xauDxSpoBCfHXHjp12SsuMqzyOHt"





