spring:
  application:
    name: hr-app

  datasource:
    url: jdbc:postgresql://localhost:5432/hr_db?currentSchema=app
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: app  # tell Hibernate that NEW tables it generates belong in `app`

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/RH-Realm  # 👈 This is the public URL for JWT validation
#          jwk-set-uri: http://localhost:9090/realms/RH-Realm/protocol/openid-connect/certs

  mail:
    host: smtp.gmail.com
    port: 587
    username: dachraouia193@gmail.com
    password: iiun fhvz ertn dopm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

file:
  upload-dir: ./uploads

server:
  port: 8083

#logging:
#  level:
#    root: INFO
#    org.springframework.security: DEBUG
#    org.springframework.web: INFO
#    org.springframework.mail: DEBUG
#    com.rh_app.hr_app: DEBUG  # This enables DEBUG level logging for your application package
#    com.rh_app.hr_app.features.user.service: DEBUG  # More specific logging for user service
#    com.rh_app.hr_app.features.user.controller: DEBUG  # More specific logging for user controller
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file:
#    name: logs/hr-app.log  # This creates a log file


# ticket time to resolve
tickets:
  sla:
    overdue-hours: 72     # escalate after 3 day

# ✅ Keycloak Admin Client (for managing users/roles via Admin API)
keycloak:
  admin:
    server-url: http://localhost:9090
    realm: RH-Realm
    client-id: keycloak-admin
    client-secret: "6Sj9xauDxSpoBCfHXHjp12SsuMqzyOHt"





