spring:
  application:
    name: hr-app

  datasource:
    url: jdbc:postgresql://localhost:5432/hr_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/RH-Realm  # 👈 This is the public URL for JWT validation

  mail:
    host: smtp.gmail.com
    port: 587
    username: dachraouia193@gmail.com
    password: iiun fhvz ertn dopm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8083

# ✅ Keycloak Admin Client (for managing users/roles via Admin API)
keycloak:
  admin:
    server-url: http://localhost:9090
    realm: RH-Realm
    client-id: keycloak-admin
    client-secret: "6Sj9xauDxSpoBCfHXHjp12SsuMqzyOHt"



